---
title: "Chinese Herbal Medicine(CHM) Theories"
---
#### **This page is not for collecting all the CHM knowledges, but to give quick references to the things have been studied.**

<br>

## **Fundamental CHM Philosophies**

<br>

#### **Yin-Yang (阴阳):**

- Negative (阴):
- Positive (阳):
  
#### **Five Elements 五行:**

- Metal (金): 
- Wood (木):
- Earth (土):
- Water (水):
- Fire (火):

#### **Table of Matching Herbal Medicine Concepts with Five Elements**

- the promotes & Inhibits in below table are in the logic that the elements in the title cell will promote/inhibit the elements in their lower rows
- the other concepts (except the promotes & inhibit rows) were matched to the Five Elements or at best (if there are >5 elements of the concept)
  - eg. the Lung was considered having the 'Metal' character, and the Liver was considered having the 'Wood' character.

<br>

| **五行(FiveElements)** | **金(Metal)** | **木(Wood)** | **土(Earth)** | **水(Water)** | **火(Fire)** | **注释** |
|:----|:--:|:--:|:--:|:--:|:--:|:----:|
| **相生(Promote)** | 水(Water) | 火(Fire) | 金(Metal) | 木(Wood) | 土(Earth) | |
| **相克(Inhibit)** | 木(Wood) | 土(Earth) | 水(Water) | 火(Fire) | 金(Metal) | |
| **五脏(Five Solid Organs)** | 肺(Lung) | 肝(Liver) | 脾(Spleen) | 肾(Kidney) | 心(Heart)| |
| **六腑(Six Hallow Organs)** | 大肠(Large Intestine) | 胆(Gallbladder) | 胃(Stomach) | 膀胱(Bladder) | 小肠(Small Intestine) | 三焦(Sanjiao)不对任一五行|
| **奇恒之腑(Special Organs)** | 脑(Brain) | 髓(Marrow) | 女子胞(Uterus & Ovaries) | 骨(Bone) | 脉(Vessels) | |
| **药味(Herb Tastes)** | 辛(Spicy) | 酸(涩)(Sour) | 甘(Sweet) | 咸(Salty) | 苦(Bitter) | 平(Plain)不对任一五行 |


#### **Five Solid Organs 五脏**

- 心(Heart)
- 肝(Liver)
- 脾(Spleen)
- 肺(Lung)
- 肾(Kidney)

#### **Six Hollow Organs 六腑**

- 大肠 (Large Intestine)
- 胆 (Gallbladder)
- 膀胱 (Bladder)
- 小肠 (Small Intestine)
- 胃 (Stomach)
- 三焦 (Sanjiao)

#### **Six Channel Terms 六经**

- 太阳(Major Positive) > 阳明(Medium Positive) > 少阳(Minor Positive) ; 
- 太阴(Major Negative) > 少阴(Medium Negative) > 厥阴(Minor Negative) ;

#### **Six Disease Elements 六邪**

- 风 (Wind)
- 寒 (Cold)
- 暑 (Heat)
- 湿 (Wet)
- 燥 (Dry)
- 火 (Fire)

#### **Seven Emotions 七情**

- 喜(Happy)
- 怒(Angry)
- 忧(Worry)
- 思(Thought)
- 悲(Sorrow)
- 恐(Scary)
- 惊(Shocked)

#### **Eight Channels/Routes 八脉**

- 督脉 任脉 冲脉 带脉 阴维脉 阳维脉 阴跷脉 阳跷脉

#### **Twelve Formal Channels 十二正经**

- 手太阴-肺 (Hand-Major Negative-Lung)
- 手厥阴-心包 (Hand-Minor Negative-Pericardium)
- 手少阴-心 (Hand-Medium Negative-Heart)
- 手阳明-大肠 (Hand-Medium Positive-Large Intestine)
- 手少阳-三焦 (Hand-Minor Positive-Sanjiao)
- 手太阳-小肠 (Hand-Major Positive-Small Intestine)
- 足太阴-脾 (Foot-Major Negative-Spleen)
- 足厥阴-肝 (Foot-Minor Negative-Liver)
- 足少阴-肾 (Foot-Medium Negative-Kidney)
- 足阳明-胃 (Foot-Medium Positive-Stomach)
- 足少阳-胆 (Foot-Minor Positive-Gallbladder)
- 足太阳-膀胱 (Foot-Major Positive-Bladder)

---

## **Terms in Herbs**

<br>

#### **Herb Property, Taste & Attributes**

- **Herb Property(药性)**
  - 4 Basic Properties: 
    - 寒 (Cold)
    - 热 (Hot)
    - 温 (Warm)
    - 凉 (Cool)
  - Extended/Variation Properties: 
    - 大寒 (Major Cold)
    - 微寒 (Minor Cold)
    - 大热 (Major Hot)
    - 微热 (Minor Hot)
    - 大温 (Major Warm)
    - 微温 (Minor Warm)

- **Herb Taste(药味)**
  - 5 Basic Tastes: 
    - 酸 (Sour)
    - 苦 (Bitter)
    - 甘 (Sweet)
    - 辛 (Spicy)
    - 咸 (Salty)
  - Extended/Variation Tastes: 大苦 (Major Bitter), 微苦 (Minor Bitter), 微辛 (Minor Spicy), 微酸 (Minor Sour),  微咸 (Minor Salty), 涩 (Astringent), 微涩 (Minor Astringent), 麻 (Numb), 微麻 (Minor Numb), 淡 (Light), 平 (Plain)

- **Attributes(归经)**
  - 心 (Heart)
  - 肝 (Liver)
  - 脾 (Spleen)
  - 肺 (Lung)
  - 肾 (Kidney)
  
#### **Seven Types of Herb Usage & Reactions 七情和合**

- 单行 (Single Usage)：一味药独立发挥左用。如独参汤、独圣丸(五灵脂)、首乌片
- 相须 (Similar Function & Promote Each Other)：两种左用相似的药配伍，有相互协同的左用。如大黄&芒硝，乳香&没药，当归&白芍
- 相使 (Different Function & Promote Each Other)：两种左用不同的药配伍，可相互促进。如黄芪&茯苓，白术&防风，巴戟天&覆盆子
- 相畏 (One Suppress the Other's Strength)：一种药能抑制或减轻另一种药的烈性。如，桔梗畏白芨，远志畏真珠，丁香畏郁金
- 相杀 (One Suppress the Other's Toxicity)：一种药能减轻或消除另一种药的毒性。如，大黄与附子，甘遂与芍药、石膏与粳米
- 相恶 (One Deactivates the Other's Efficacy/Effectiveness)：两种药合用会降低或丧失药效，属配伍禁忌。如，元参恶干姜，巴戟恶雷丸，狗脊恶败酱
- 相反 (Cause Toxicity when Use Together)：两种药何用能产生毒副作用，属配伍禁忌。如，乌头反半夏，大戟反芫花，细辛反藜芦

---

## **Terms in Pulses 脉象**

<br>

#### **Pulse Properties & Patterns:(quoted from [Baidu Baike](https://baike.baidu.com/item/%E8%84%89%E8%B1%A1/3029072))**

###### **(Normal Pulse is Like: 一次呼吸跳4次；寸关尺三部有脉，脉不浮不沉，和缓有力，尺脉沉取有力)**

- 位:脉搏跳动显现的部位和长度

  - 浮:脉位表浅，轻按可得，重按则减。
       主病：表证由于外感病邪停留于表时，卫气抗邪，脉气鼓动于外，故脉位浅显。
       浮而有力为表实；浮而无力为表虚。
       内伤久病因阴血衰少，阳气不足，虚阳外浮，脉浮大无力为危证。
  - 沉:脉位深沉，轻按不得，重按乃得。
       主病：里证。
       有力为里实，无力为里虚。
       邪郁于里，气血阻滞阳气不畅，脉沉有力为里实；脏腑虚弱，阳虚气陷，脉气鼓动无力，则脉沉无力。
  - 长:脉搏超过寸、关、尺三部
  - 短:脉动不及寸、尺者
  
- 数:脉搏跳动的至数和节律

  - 数:一(呼)息5至以上（每分钟脉搏在90次以上），脉搏急促。
       主病：热证。
       有力为实热，无力为虚热。
       外感热病初起，脏腑热盛，邪热鼓动，血行加速，脉快有力为实热；阴虚火旺，津血不足，虚热内生，脉快而无力为虚热。
  - 迟:一息不满4至以下（每分钟脉搏在60次以下），脉搏缓慢。
       主病：寒证。
       有力为实寒，无力为虚寒。
       寒则凝滞，气血运行缓慢，脉迟而有力为实寒证；阳气虚损，无力运行气血，脉迟而无力，为虚寒证。
  - 促:有间歇，脉来急数，时而一止，止无定数，即脉搏快有不规则的间歇。
       为阳盛热实，或气血痰食停滞，见于气血痰食瘀滞，肿痛，诸实热证。脉细促而无力，多为虚脱之象。
  - 结:有间歇，脉来缓慢，时见一止，止无定数，即脉搏慢而不规则的间歇。
       为阴盛寒积或气血瘀滞，见于气滞血瘀，痰结食积，症积、疝痛等。
       结而无力为气血虚衰，见于虚劳久病及各类心脏病所致的心律不齐。
  - 代:有间歇，脉来歇止，止有定数，不能自还，良久复动，即有规律的间歇，脉搏动到一定至数歇止一次，歇止时间较长。
       为脏气衰微之征象。
       可见于心律失常的二联律，三联律等。
  - [散](https://baike.baidu.com/item/%E6%95%A3%E8%84%89/7480897):脉浮散无根，轻按有分散零乱之感，中按渐空，重按则无。
       主元气离散，胃气衰败，气血消亡，精气将绝，见于病情垂危阶段。
  - 涩:脉率快慢不匀，三五不调
  
- 形:脉搏跳动宽度等形态

  - 洪:脉管充盈，脉搏幅度较大
  - 细:脉管充盈度较小，搏动幅度较小
  - 弦:脉管弹性差，欠柔和
  - 濡:脉体柔软无力
  - 缓:脉体柔软无力
  
- 势:脉搏应指的强弱、流畅等趋势。受脉动轴向和径向力度，心脏&阻力影响的流利度，血管弹性&张力影响的紧张度等因素的影响

  - 实:应指有力
  - 虚:应指无力
  - 滑:通畅状态好，脉来流利圆滑
  - 涩:通畅状态差，脉来艰涩不畅
